languageCode = "en-us"
title = "Richard Scott"
baseURL = "https://architectureaboutdancing.github.io/"
theme = "code-editor"

[blackfriday]
    fractions = false

[params]
    author = "Richard Scott"
    locale = "en-US"
    DateForm = "2.1.2006"
